# 0. primer_seqs.sh

# This is not a command to run; this file contains all the information about primers and primer sequences that you may want to select from using the command line call; this script can be edited to add additional information in the same format that it is set up for GNU BASH langauge.

# Each primer set (F and R) is given a number; here is the format used to specify seq, rev comp seq, and length min and max parameters:

declare -a ARRAY_FOLDERS
declare -a PRIMERS_F
declare -a PRIMERS_R
declare -a PRIMERS_FRC
declare -a PRIMERS_RRC
declare -a PRODUCT_LENGTH_MIN
declare -a PRODUCT_LENGHT_MAX

# 18S
# 965 GGCGATCAGATACCGCCCTAGTT
# 965 (revcomp) AACTAGGGCGGTATCTGATCGCC
# 1573 TACAAAGGGCAGGGACGTAAT
# 1573 (revcomp) ATTACGTCCCTGCCCTTTGTA
ARRAY_FOLDERS[0]="18S"
PRIMERS_F[0]="GGCGATCAGATACCGCCCTAGTT"
PRIMERS_FRC[0]="AACTAGGGCGGTATCTGATCGCC"
PRIMERS_R[0]="TACAAAGGGCAGGGACGTAAT"
PRIMERS_RRC[0]="ATTACGTCCCTGCCCTTTGTA"
PRODUCT_LENGTH_MIN[0]="300"
PRODUCT_LENGTH_MAX[0]="800"

# BT
# BT2A ggtaaccaaatcggtgctgctttc
# BT2A (revcomp) gaaagcagcaccgatttggttacc
# BT2B accctcagtgtagtgacccttggc
# BT2B (revcomp) gccaagggtcactacactgagggt
ARRAY_FOLDERS[1]="BT"
PRIMERS_F[1]="ggtaaccaaatcggtgctgctttc"
PRIMERS_FRC[1]="gaaagcagcaccgatttggttacc"
PRIMERS_R[1]="accctcagtgtagtgacccttggc"
PRIMERS_RRC[1]="gccaagggtcactacactgagggt"
PRODUCT_LENGTH_MIN[1]="400"
PRODUCT_LENGTH_MAX[1]="1000"

# COI3P
# S1718 GGAGGATTTGGAAATTGATTAGTTCC
# A2411 GCTAATCATCTAAAAACTTTAATTCC(WGTWG)
# S1718(revcomp) GGAACTAATCAATTTCCAAATCCTCC
# A2411(revcomp) GGAATTAAAGTTTTTAGATGATTAGC
# A1718 GGAGGATTTGGAAATTGATTAGTTCC
# A1718 (revcomp) GGAACTAATCAATTTCCAAATCCTCC
# A2411 GCTAATCATCTAAAAACTTTAATTCCWGTWG
# A2411 (revcomp) CWACWGGAATTAAAGTTTTTAGATGATTAGC

ARRAY_FOLDERS[2]="COI3P"
PRIMERS_F[2]="GGAGGATTTGGAAATTGATTAGTTCC"
PRIMERS_FRC[2]="GGAACTAATCAATTTCCAAATCCTCC"
PRIMERS_R[2]="GCTAATCATCTAAAAACTTTAATTCCWGTWG"
PRIMERS_RRC[2]="CWACWGGAATTAAAGTTTTTAGATGATTAGC"
PRODUCT_LENGTH_MIN[2]="400"
PRODUCT_LENGTH_MAX[2]="1200"

# ITS1F4
# ITS1F CTTGGTCATTTAGAGGAAGTAA
# ITS4 TCCTCCGCTTATTGATATGC
# ITS1F(revcomp) TTACTTCCTCTAAATGACCAAG
# ITS4(revcomp) GCATATCAATAAGCGGAGGA
ARRAY_FOLDERS[3]="ITS1F4"
PRIMERS_F[3]="CTTGGTCATTTAGAGGAAGTAA"
PRIMERS_FRC[3]="TTACTTCCTCTAAATGACCAAG"
PRIMERS_R[3]="TCCTCCGCTTATTGATATGC"
PRIMERS_RRC[3]="GCATATCAATAAGCGGAGGA"
PRODUCT_LENGTH_MIN[3]="250"
PRODUCT_LENGTH_MAX[3]="1200"

# ITS54
# ITS5 GGAAGTAAAAGTCGTAACAAGG
# ITS5(revcomp) CCTTGTTACGACTTTTACTTCC
ARRAY_FOLDERS[4]="ITS54"
PRIMERS_F[4]="GGAAGTAAAAGTCGTAACAAGG"
PRIMERS_FRC[4]="CCTTGTTACGACTTTTACTTCC"
PRIMERS_R[4]="TCCTCCGCTTATTGATATGC"
PRIMERS_RRC[4]="GCATATCAATAAGCGGAGGA"
PRODUCT_LENGTH_MIN[4]="300"
PRODUCT_LENGTH_MAX[4]="1200"

# ITS14
# ITS1 TCCGTAGGTGAACCTGCGG
# ITS1(revcomp) CCGCAGGTTCACCTACGGA
ARRAY_FOLDERS[5]="ITS14"
PRIMERS_F[5]="TCCGTAGGTGAACCTGCGG"
PRIMERS_FRC[5]="CCGCAGGTTCACCTACGGA"
PRIMERS_R[5]="TCCTCCGCTTATTGATATGC"
PRIMERS_RRC[5]="GCATATCAATAAGCGGAGGA"
PRODUCT_LENGTH_MIN[5]="400"
PRODUCT_LENGTH_MAX[5]="900"

# LepCOI
# LepF1 ATTCAACCAATCATAAAGATAT
# LepF1 (revcomp) ATATCTTTATGATTGGTTGAAT
# LepR1 TAAACTTCTGGATGTCCAAAAA
# LepR1 (revcomp) TTTTTGGACATCCAGAAGTTTA
ARRAY_FOLDERS[6]="LepCOI"
PRIMERS_F[6]="ATTCAACCAATCATAAAGATAT"
PRIMERS_FRC[6]="ATATCTTTATGATTGGTTGAAT"
PRIMERS_R[6]="TAAACTTCTGGATGTCCAAAAA"
PRIMERS_RRC[6]="TTTTTGGACATCCAGAAGTTTA"
PRODUCT_LENGTH_MIN[6]="400"
PRODUCT_LENGTH_MAX[6]="1000"

# LSU
# LR0R ACCCGCTGAACTTAAGC
# LR0R (revcomp) GCTTAAGTTCAGCGGGT
# LR5 TCCTGAGGGAAACTTCG
# LR5 (revcomp) CGAAGTTTCCCTCAGGA
ARRAY_FOLDERS[7]="LSU"
PRIMERS_F[7]="ACCCGCTGAACTTAAGC"
PRIMERS_FRC[7]="GCTTAAGTTCAGCGGGT"
PRIMERS_R[7]="TCCTGAGGGAAACTTCG"
PRIMERS_RRC[7]="CGAAGTTTCCCTCAGGA"
PRODUCT_LENGTH_MIN[7]="500"
PRODUCT_LENGTH_MAX[7]="1600"

# TEF
# 728 CATCGAGAAGTTCGAGAAGG
# 728 (revcomp) CCTTCTCGAACTTCTCGATG
# 1567 ACHGTRCCRATACCACCRATCTT
# 1567 (revcomp) AAGATYGGTGGTATYGGYACDGT
ARRAY_FOLDERS[8]="TEF"
PRIMERS_F[8]="CATCGAGAAGTTCGAGAAGG"
PRIMERS_FRC[8]="CCTTCTCGAACTTCTCGATG"
PRIMERS_R[8]="ACHGTRCCRATACCACCRATCTT"
PRIMERS_RRC[8]="AAGATYGGTGGTATYGGYACDGT"
PRODUCT_LENGTH_MIN[8]="550"
PRODUCT_LENGTH_MAX[8]="1000"
length=9 # not doing 16S yet
#readarray -t barcodes < barcodes.txt
#readarray -t primers < primers.txt

ARRAY_FOLDERS[9]="16S"
PRIMERS_F[9]="AGAGTTTGATCMTGGCTCAG"
PRIMERS_R[9]="GGTTACCTTGTTACGACTT"
PRIMERS_RRC[9]="AAGTCGTAACAAGGTAACC"
PRODUCT_LENGTH_MIN[9]="500"
PRODUCT_LENGTH_MAX[9]="1500"

# ITS1FLR3
ARRAY_FOLDERS[10]="ITS1FLR3"
PRIMERS_F[10]="CTTGGTCATTTAGAGGAAGTAA"
PRIMERS_R[10]="CCGTGTTTCAAGACGGG"
PRIMERS_RRC[10]="CCCGTCTTGAAACACGG"
PRODUCT_LENGTH_MIN[10]="250"
PRODUCT_LENGTH_MAX[10]="1800"